VAGRANT_BOX_NAME = "centos/7"

# Creating two nodes. Change this according to the number of nodes you want
CENTOS_NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..CENTOS_NODES).each do |i|
        config.vm.define "centos-node-#{i}" do |node|
            node.vm.box = VAGRANT_BOX_NAME

            # setting the network parameters
            node.vm.network "private_network", ip: "192.168.53.#{i + 60}"

            # naming the nodes
            node.vm.hostname = "centos-node-#{i}"

            # stating provider, memory and cpu capacity 
            node.vm.provider :virtualbox do |vb|
                vb.name = "centos-node-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
            
        end

    end

    config.vm.define "centos-control" do |control|
        control.vm.box = VAGRANT_BOX_NAME

        # setting the network parameters
        control.vm.network "private_network", ip: "192.168.53.51"
                
        # naming the control virtualmachine
        control.vm.hostname = "centos-control"

        # stating provider, memory and cpu capacity 
        control.vm.provider :virtualbox do |vb|
            vb.name = "centos-control"
            vb.memory = 2048
            vb.cpus = 1
        end

    end
        
end
