IMAGE_NAME = "centos/7"

# Creating two nodes. Change this according to the number of nodes you want to create
CENTOS_NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..CENTOS_NODES).each do |i|
        config.vm.define "centos-node-#{i}" do |centosnode|
            centosnode.vm.box = IMAGE_NAME
            centosnode.vm.network "private_network", ip: "192.168.43.#{i + 60}", virtualbox__intnet: "intnet"
            centosnode.vm.hostname = "centos-node-#{i}"

            # naming the virtualmachine
            centosnode.vm.provider :virtualbox do |vb|
                vb.name = "centos-node-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
            
        end
    end

    config.vm.define "centos-control" do |centoscontrol|
        centoscontrol.vm.box = IMAGE_NAME
        centoscontrol.vm.network "private_network", ip: "192.168.43.51", virtualbox__intnet: "intnet"

                
        # naming the virtualmachine
        centoscontrol.vm.hostname = "centos-control"

        centoscontrol.vm.provider :virtualbox do |vb|
            vb.name = "centos-control"
            vb.memory = 2048
            vb.cpus = 1
        end

    end
        
end
