VAGRANT_BOX_NAME = "ubuntu/focal64"

# Creating three nodes. Change this according to the number of nodes you want
UBUNTU_NODES = 3

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..UBUNTU_NODES).each do |i|
        config.vm.define "ubuntu-node-#{i}" do |node|
            node.vm.box = VAGRANT_BOX_NAME

            # setting the network parameters
            node.vm.network "private_network", ip: "192.168.53.#{i + 20}"

            # naming the nodes
            node.vm.hostname = "ubuntu-node-#{i}"

            # stating provider, memory and cpu capacity 
            node.vm.provider :virtualbox do |vb|
                vb.name = "ubuntu-node-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
            
        end

    end

    config.vm.define "ubuntu-control" do |control|
        control.vm.box = VAGRANT_BOX_NAME

        # setting the network parameters
        control.vm.network "private_network", ip: "192.168.53.11"

        # naming the contol virtualmachine
        control.vm.hostname = "ubuntu-control"

        # stating provider, memory and cpu capacity 
        control.vm.provider :virtualbox do |vb|
            vb.name = "ubuntu-control"
            vb.memory = 2048
            vb.cpus = 1
        end
    
    end
        
end
