IMAGE_NAME = "ubuntu/focal64"

# Creating two nodes. Change this according to the number of nodes you want to create
UBUNTU_NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..UBUNTU_NODES).each do |i|
        config.vm.define "ubuntu-node-#{i}" do |ubuntunode|
            ubuntunode.vm.box = IMAGE_NAME
            ubuntunode.vm.network "private_network", ip: "192.168.43.#{i + 20}"

            # naming the virtualmachine
            ubuntunode.vm.hostname = "ubuntu-node-#{i}"
            ubuntunode.vm.provider :virtualbox do |vb|
                vb.name = "ubuntu-node-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end
            
        end

    end

    config.vm.define "ubuntu-control" do |ubuntucontrol|
        ubuntucontrol.vm.box = IMAGE_NAME
        ubuntucontrol.vm.network "private_network", ip: "192.168.43.11"

        # naming the virtualmachine
        ubuntucontrol.vm.hostname = "ubuntu-control"
        ubuntucontrol.vm.provider :virtualbox do |vb|
            vb.name = "ubuntu-control"
            vb.memory = 2048
            vb.cpus = 1
        end
    
    end
        
end
